import { ROUTERS } from './router';

export const PUBLIC_ROUTES = [
  ROUTERS.HOME,
  ROUTERS.LOGIN,
  ROUTERS.RESTAURANT,
  ROUTERS.PRODUCT_DETAIL,
];

export const PRIVATE_ROUTES = [ROUTERS.CART, ROUTERS.PROFILE];
